use super::super::helper::SqlLanguage;

#[derive(Clone, Copy, Debug)]
pub(crate) enum StringType {
    DoubleQuote,
    SingleQuote,
    Backtick,
    Brackets,
    NSingle,
    UAndSingle,
    UAndDouble,
    Dollar,
    Brace,
}

#[derive(Clone, Copy, Debug)]
pub(crate) enum OverrideKind {
    None,
    Spark,
    PlSql,
}

#[derive(Clone, Copy)]
pub(crate) struct Dialect {
    pub reserved_words: &'static [&'static str],
    pub reserved_top_level: &'static [&'static str],
    pub reserved_newline: &'static [&'static str],
    pub reserved_top_level_no_indent: &'static [&'static str],
    pub string_types: &'static [StringType],
    pub open_parens: &'static [&'static str],
    pub close_parens: &'static [&'static str],
    pub indexed_placeholders: &'static [char],
    pub named_placeholders: &'static [char],
    pub line_comments: &'static [&'static str],
    pub special_word_chars: &'static [char],
    pub extra_operators: &'static [&'static str],
    pub override_kind: OverrideKind,
}

pub(crate) fn dialect(language: SqlLanguage) -> &'static Dialect {
    match language {
        SqlLanguage::Sql => &SQL,
        SqlLanguage::Tsql => &TSQL,
        SqlLanguage::Spark => &SPARK,
        SqlLanguage::RedShift => &REDSHIFT,
        SqlLanguage::PostgreSql => &POSTGRES,
        SqlLanguage::PlSql => &PLSQL,
        SqlLanguage::N1ql => &N1QL,
        SqlLanguage::MySql => &MYSQL,
        SqlLanguage::MariaDb => &MARIADB,
        SqlLanguage::Db2 => &DB2,
    }
}

mod sql {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "ABS",
        "ALL",
        "ALLOCATE",
        "ALTER",
        "AND",
        "ANY",
        "ARE",
        "ARRAY",
        "AS",
        "ASENSITIVE",
        "ASYMMETRIC",
        "AT",
        "ATOMIC",
        "AUTHORIZATION",
        "AVG",
        "BEGIN",
        "BETWEEN",
        "BIGINT",
        "BINARY",
        "BLOB",
        "BOOLEAN",
        "BOTH",
        "BY",
        "CALL",
        "CALLED",
        "CARDINALITY",
        "CASCADED",
        "CASE",
        "CAST",
        "CEIL",
        "CEILING",
        "CHAR",
        "CHAR_LENGTH",
        "CHARACTER",
        "CHARACTER_LENGTH",
        "CHECK",
        "CLOB",
        "CLOSE",
        "COALESCE",
        "COLLATE",
        "COLLECT",
        "COLUMN",
        "COMMIT",
        "CONDITION",
        "CONNECT",
        "CONSTRAINT",
        "CONVERT",
        "CORR",
        "CORRESPONDING",
        "COUNT",
        "COVAR_POP",
        "COVAR_SAMP",
        "CREATE",
        "CROSS",
        "CUBE",
        "CUME_DIST",
        "CURRENT",
        "CURRENT_CATALOG",
        "CURRENT_DATE",
        "CURRENT_DEFAULT_TRANSFORM_GROUP",
        "CURRENT_PATH",
        "CURRENT_ROLE",
        "CURRENT_SCHEMA",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_TRANSFORM_GROUP_FOR_TYPE",
        "CURRENT_USER",
        "CURSOR",
        "CYCLE",
        "DATE",
        "DAY",
        "DEALLOCATE",
        "DEC",
        "DECIMAL",
        "DECLARE",
        "DEFAULT",
        "DELETE",
        "DENSE_RANK",
        "DEREF",
        "DESCRIBE",
        "DETERMINISTIC",
        "DISCONNECT",
        "DISTINCT",
        "DOUBLE",
        "DROP",
        "DYNAMIC",
        "EACH",
        "ELEMENT",
        "ELSE",
        "END",
        "END-EXEC",
        "ESCAPE",
        "EVERY",
        "EXCEPT",
        "EXEC",
        "EXECUTE",
        "EXISTS",
        "EXP",
        "EXTERNAL",
        "EXTRACT",
        "FALSE",
        "FETCH",
        "FILTER",
        "FLOAT",
        "FLOOR",
        "FOR",
        "FOREIGN",
        "FREE",
        "FROM",
        "FULL",
        "FUNCTION",
        "FUSION",
        "GET",
        "GLOBAL",
        "GRANT",
        "GROUP",
        "GROUPING",
        "HAVING",
        "HOLD",
        "HOUR",
        "IDENTITY",
        "IN",
        "INDICATOR",
        "INNER",
        "INOUT",
        "INSENSITIVE",
        "INSERT",
        "INT",
        "INTEGER",
        "INTERSECT",
        "INTERSECTION",
        "INTERVAL",
        "INTO",
        "IS",
        "JOIN",
        "LANGUAGE",
        "LARGE",
        "LATERAL",
        "LEADING",
        "LEFT",
        "LIKE",
        "LIKE_REGEX",
        "LN",
        "LOCAL",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "LOWER",
        "MATCH",
        "MAX",
        "MEMBER",
        "MERGE",
        "METHOD",
        "MIN",
        "MINUTE",
        "MOD",
        "MODIFIES",
        "MODULE",
        "MONTH",
        "MULTISET",
        "NATIONAL",
        "NATURAL",
        "NCHAR",
        "NCLOB",
        "NEW",
        "NO",
        "NONE",
        "NORMALIZE",
        "NOT",
        "NULL",
        "NULLIF",
        "NUMERIC",
        "OCTET_LENGTH",
        "OCCURRENCES_REGEX",
        "OF",
        "OLD",
        "ON",
        "ONLY",
        "OPEN",
        "OR",
        "ORDER",
        "OUT",
        "OUTER",
        "OVER",
        "OVERLAPS",
        "OVERLAY",
        "PARAMETER",
        "PARTITION",
        "PERCENT_RANK",
        "PERCENTILE_CONT",
        "PERCENTILE_DISC",
        "POSITION",
        "POSITION_REGEX",
        "POWER",
        "PRECISION",
        "PREPARE",
        "PRIMARY",
        "PROCEDURE",
        "RANGE",
        "RANK",
        "READS",
        "REAL",
        "RECURSIVE",
        "REF",
        "REFERENCES",
        "REFERENCING",
        "REGR_AVGX",
        "REGR_AVGY",
        "REGR_COUNT",
        "REGR_INTERCEPT",
        "REGR_R2",
        "REGR_SLOPE",
        "REGR_SXX",
        "REGR_SXY",
        "REGR_SYY",
        "RELEASE",
        "RESULT",
        "RETURN",
        "RETURNS",
        "REVOKE",
        "RIGHT",
        "ROLLBACK",
        "ROLLUP",
        "ROW",
        "ROW_NUMBER",
        "ROWS",
        "SAVEPOINT",
        "SCOPE",
        "SCROLL",
        "SEARCH",
        "SECOND",
        "SELECT",
        "SENSITIVE",
        "SESSION_USER",
        "SET",
        "SIMILAR",
        "SMALLINT",
        "SOME",
        "SPECIFIC",
        "SPECIFICTYPE",
        "SQL",
        "SQLEXCEPTION",
        "SQLSTATE",
        "SQLWARNING",
        "SQRT",
        "START",
        "STATIC",
        "STDDEV_POP",
        "STDDEV_SAMP",
        "SUBMULTISET",
        "SUBSTRING",
        "SUBSTRING_REGEX",
        "SUM",
        "SYMMETRIC",
        "SYSTEM",
        "SYSTEM_USER",
        "TABLE",
        "TABLESAMPLE",
        "THEN",
        "TIME",
        "TIMESTAMP",
        "TIMEZONE_HOUR",
        "TIMEZONE_MINUTE",
        "TO",
        "TRAILING",
        "TRANSLATE",
        "TRANSLATE_REGEX",
        "TRANSLATION",
        "TREAT",
        "TRIGGER",
        "TRIM",
        "TRUE",
        "UESCAPE",
        "UNION",
        "UNIQUE",
        "UNKNOWN",
        "UNNEST",
        "UPDATE",
        "UPPER",
        "USER",
        "USING",
        "VALUE",
        "VALUES",
        "VAR_POP",
        "VAR_SAMP",
        "VARBINARY",
        "VARCHAR",
        "VARYING",
        "WHEN",
        "WHENEVER",
        "WHERE",
        "WIDTH_BUCKET",
        "WINDOW",
        "WITH",
        "WITHIN",
        "WITHOUT",
        "YEAR",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "ALTER COLUMN",
        "ALTER TABLE",
        "CASE",
        "DELETE FROM",
        "END",
        "FETCH FIRST",
        "FETCH NEXT",
        "FETCH PRIOR",
        "FETCH LAST",
        "FETCH ABSOLUTE",
        "FETCH RELATIVE",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INSERT INTO",
        "LIMIT",
        "ORDER BY",
        "SELECT",
        "SET SCHEMA",
        "SET",
        "UPDATE",
        "VALUES",
        "WHERE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "ELSE",
        "OR",
        "WHEN",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "FULL JOIN",
        "FULL OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "INTERSECT",
        "INTERSECT ALL",
        "INTERSECT DISTINCT",
        "UNION",
        "UNION ALL",
        "UNION DISTINCT",
        "EXCEPT",
        "EXCEPT ALL",
        "EXCEPT DISTINCT",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::NSingle, StringType::SingleQuote, StringType::Backtick, StringType::Brackets],
        open_parens: &["(", "CASE"],
        close_parens: &[")", "END"],
        indexed_placeholders: &['?'],
        named_placeholders: &['@'],
        line_comments: &["--"],
        special_word_chars: &['#', '@', '$'],
        extra_operators: &[],
        override_kind: OverrideKind::None,
    };
}

pub(crate) static SQL: Dialect = sql::DIALECT;

mod tsql {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "ADD",
        "EXTERNAL",
        "PROCEDURE",
        "ALL",
        "FETCH",
        "PUBLIC",
        "ALTER",
        "FILE",
        "RAISERROR",
        "AND",
        "FILLFACTOR",
        "READ",
        "ANY",
        "FOR",
        "READTEXT",
        "AS",
        "FOREIGN",
        "RECONFIGURE",
        "ASC",
        "FREETEXT",
        "REFERENCES",
        "AUTHORIZATION",
        "FREETEXTTABLE",
        "REPLICATION",
        "BACKUP",
        "FROM",
        "RESTORE",
        "BEGIN",
        "FULL",
        "RESTRICT",
        "BETWEEN",
        "FUNCTION",
        "RETURN",
        "BREAK",
        "GOTO",
        "REVERT",
        "BROWSE",
        "GRANT",
        "REVOKE",
        "BULK",
        "GROUP",
        "RIGHT",
        "BY",
        "HAVING",
        "ROLLBACK",
        "CASCADE",
        "HOLDLOCK",
        "ROWCOUNT",
        "CASE",
        "IDENTITY",
        "ROWGUIDCOL",
        "CHECK",
        "IDENTITY_INSERT",
        "RULE",
        "CHECKPOINT",
        "IDENTITYCOL",
        "SAVE",
        "CLOSE",
        "IF",
        "SCHEMA",
        "CLUSTERED",
        "IN",
        "SECURITYAUDIT",
        "COALESCE",
        "INDEX",
        "SELECT",
        "COLLATE",
        "INNER",
        "SEMANTICKEYPHRASETABLE",
        "COLUMN",
        "INSERT",
        "SEMANTICSIMILARITYDETAILSTABLE",
        "COMMIT",
        "INTERSECT",
        "SEMANTICSIMILARITYTABLE",
        "COMPUTE",
        "INTO",
        "SESSION_USER",
        "CONSTRAINT",
        "IS",
        "SET",
        "CONTAINS",
        "JOIN",
        "SETUSER",
        "CONTAINSTABLE",
        "KEY",
        "SHUTDOWN",
        "CONTINUE",
        "KILL",
        "SOME",
        "CONVERT",
        "LEFT",
        "STATISTICS",
        "CREATE",
        "LIKE",
        "SYSTEM_USER",
        "CROSS",
        "LINENO",
        "TABLE",
        "CURRENT",
        "LOAD",
        "TABLESAMPLE",
        "CURRENT_DATE",
        "MERGE",
        "TEXTSIZE",
        "CURRENT_TIME",
        "NATIONAL",
        "THEN",
        "CURRENT_TIMESTAMP",
        "NOCHECK",
        "TO",
        "CURRENT_USER",
        "NONCLUSTERED",
        "TOP",
        "CURSOR",
        "NOT",
        "TRAN",
        "DATABASE",
        "NULL",
        "TRANSACTION",
        "DBCC",
        "NULLIF",
        "TRIGGER",
        "DEALLOCATE",
        "OF",
        "TRUNCATE",
        "DECLARE",
        "OFF",
        "TRY_CONVERT",
        "DEFAULT",
        "OFFSETS",
        "TSEQUAL",
        "DELETE",
        "ON",
        "UNION",
        "DENY",
        "OPEN",
        "UNIQUE",
        "DESC",
        "OPENDATASOURCE",
        "UNPIVOT",
        "DISK",
        "OPENQUERY",
        "UPDATE",
        "DISTINCT",
        "OPENROWSET",
        "UPDATETEXT",
        "DISTRIBUTED",
        "OPENXML",
        "USE",
        "DOUBLE",
        "OPTION",
        "USER",
        "DROP",
        "OR",
        "VALUES",
        "DUMP",
        "ORDER",
        "VARYING",
        "ELSE",
        "OUTER",
        "VIEW",
        "END",
        "OVER",
        "WAITFOR",
        "ERRLVL",
        "PERCENT",
        "WHEN",
        "ESCAPE",
        "PIVOT",
        "WHERE",
        "EXCEPT",
        "PLAN",
        "WHILE",
        "EXEC",
        "PRECISION",
        "WITH",
        "EXECUTE",
        "PRIMARY",
        "WITHIN GROUP",
        "EXISTS",
        "PRINT",
        "WRITETEXT",
        "EXIT",
        "PROC",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "ALTER COLUMN",
        "ALTER TABLE",
        "CASE",
        "DELETE FROM",
        "END",
        "EXCEPT",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INSERT INTO",
        "INSERT",
        "LIMIT",
        "ORDER BY",
        "SELECT",
        "SET CURRENT SCHEMA",
        "SET SCHEMA",
        "SET",
        "UPDATE",
        "VALUES",
        "WHERE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "ELSE",
        "OR",
        "WHEN",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "FULL JOIN",
        "FULL OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "INTERSECT",
        "INTERSECT ALL",
        "MINUS",
        "UNION",
        "UNION ALL",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::NSingle, StringType::SingleQuote, StringType::Backtick, StringType::Brackets],
        open_parens: &["(", "CASE"],
        close_parens: &[")", "END"],
        indexed_placeholders: &[],
        named_placeholders: &['@'],
        line_comments: &["--"],
        special_word_chars: &['#', '@', '$'],
        extra_operators: &[">=", "<=", "<>", "!=", "!<", "!>", "+=", "-=", "*=", "/=", "%=", "|=", "&=", "^=", "::"],
        override_kind: OverrideKind::None,
    };
}

pub(crate) static TSQL: Dialect = tsql::DIALECT;

mod spark {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "ALL",
        "ALTER",
        "ANALYSE",
        "ANALYZE",
        "ARRAY_ZIP",
        "ARRAY",
        "AS",
        "ASC",
        "AVG",
        "BETWEEN",
        "CASCADE",
        "CASE",
        "CAST",
        "COALESCE",
        "COLLECT_LIST",
        "COLLECT_SET",
        "COLUMN",
        "COLUMNS",
        "COMMENT",
        "CONSTRAINT",
        "CONTAINS",
        "CONVERT",
        "COUNT",
        "CUME_DIST",
        "CURRENT ROW",
        "CURRENT_DATE",
        "CURRENT_TIMESTAMP",
        "DATABASE",
        "DATABASES",
        "DATE_ADD",
        "DATE_SUB",
        "DATE_TRUNC",
        "DAY_HOUR",
        "DAY_MINUTE",
        "DAY_SECOND",
        "DAY",
        "DAYS",
        "DECODE",
        "DEFAULT",
        "DELETE",
        "DENSE_RANK",
        "DESC",
        "DESCRIBE",
        "DISTINCT",
        "DISTINCTROW",
        "DIV",
        "DROP",
        "ELSE",
        "ENCODE",
        "END",
        "EXISTS",
        "EXPLAIN",
        "EXPLODE_OUTER",
        "EXPLODE",
        "FILTER",
        "FIRST_VALUE",
        "FIRST",
        "FIXED",
        "FLATTEN",
        "FOLLOWING",
        "FROM_UNIXTIME",
        "FULL",
        "GREATEST",
        "GROUP_CONCAT",
        "HOUR_MINUTE",
        "HOUR_SECOND",
        "HOUR",
        "HOURS",
        "IF",
        "IFNULL",
        "IN",
        "INSERT",
        "INTERVAL",
        "INTO",
        "IS",
        "LAG",
        "LAST_VALUE",
        "LAST",
        "LEAD",
        "LEADING",
        "LEAST",
        "LEVEL",
        "LIKE",
        "MAX",
        "MERGE",
        "MIN",
        "MINUTE_SECOND",
        "MINUTE",
        "MONTH",
        "NATURAL",
        "NOT",
        "NOW()",
        "NTILE",
        "NULL",
        "NULLIF",
        "OFFSET",
        "ON DELETE",
        "ON UPDATE",
        "ON",
        "ONLY",
        "OPTIMIZE",
        "OVER",
        "PERCENT_RANK",
        "PRECEDING",
        "RANGE",
        "RANK",
        "REGEXP",
        "RENAME",
        "RLIKE",
        "ROW",
        "ROWS",
        "SECOND",
        "SEPARATOR",
        "SEQUENCE",
        "SIZE",
        "STRING",
        "STRUCT",
        "SUM",
        "TABLE",
        "TABLES",
        "TEMPORARY",
        "THEN",
        "TO_DATE",
        "TO_JSON",
        "TO",
        "TRAILING",
        "TRANSFORM",
        "TRUE",
        "TRUNCATE",
        "TYPE",
        "TYPES",
        "UNBOUNDED",
        "UNIQUE",
        "UNIX_TIMESTAMP",
        "UNLOCK",
        "UNSIGNED",
        "USING",
        "VARIABLES",
        "VIEW",
        "WHEN",
        "WITH",
        "YEAR_MONTH",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "AFTER",
        "ALTER COLUMN",
        "ALTER DATABASE",
        "ALTER SCHEMA",
        "ALTER TABLE",
        "CLUSTER BY",
        "CLUSTERED BY",
        "DELETE FROM",
        "DISTRIBUTE BY",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INSERT INTO",
        "INSERT",
        "LIMIT",
        "OPTIONS",
        "ORDER BY",
        "PARTITION BY",
        "PARTITIONED BY",
        "RANGE",
        "ROWS",
        "SELECT",
        "SET CURRENT SCHEMA",
        "SET SCHEMA",
        "SET",
        "TBLPROPERTIES",
        "UPDATE",
        "USING",
        "VALUES",
        "WHERE",
        "WINDOW",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "CREATE OR",
        "CREATE",
        "ELSE",
        "LATERAL VIEW",
        "OR",
        "OUTER APPLY",
        "WHEN",
        "XOR",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "FULL JOIN",
        "FULL OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
        "ANTI JOIN",
        "SEMI JOIN",
        "LEFT ANTI JOIN",
        "LEFT SEMI JOIN",
        "RIGHT OUTER JOIN",
        "RIGHT SEMI JOIN",
        "NATURAL ANTI JOIN",
        "NATURAL FULL OUTER JOIN",
        "NATURAL INNER JOIN",
        "NATURAL LEFT ANTI JOIN",
        "NATURAL LEFT OUTER JOIN",
        "NATURAL LEFT SEMI JOIN",
        "NATURAL OUTER JOIN",
        "NATURAL RIGHT OUTER JOIN",
        "NATURAL RIGHT SEMI JOIN",
        "NATURAL SEMI JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "EXCEPT ALL",
        "EXCEPT",
        "INTERSECT ALL",
        "INTERSECT",
        "UNION ALL",
        "UNION",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::SingleQuote, StringType::Backtick, StringType::Brace],
        open_parens: &["(", "CASE"],
        close_parens: &[")", "END"],
        indexed_placeholders: &['?'],
        named_placeholders: &['$'],
        line_comments: &["--"],
        special_word_chars: &[],
        extra_operators: &["!=", "<=>", "&&", "||", "=="],
        override_kind: OverrideKind::Spark,
    };
}

pub(crate) static SPARK: Dialect = spark::DIALECT;

mod redshift {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "AES128",
        "AES256",
        "ALLOWOVERWRITE",
        "ANALYSE",
        "ARRAY",
        "AS",
        "ASC",
        "AUTHORIZATION",
        "BACKUP",
        "BINARY",
        "BLANKSASNULL",
        "BOTH",
        "BYTEDICT",
        "BZIP2",
        "CAST",
        "CHECK",
        "COLLATE",
        "COLUMN",
        "CONSTRAINT",
        "CREATE",
        "CREDENTIALS",
        "CURRENT_DATE",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_USER",
        "CURRENT_USER_ID",
        "DEFAULT",
        "DEFERRABLE",
        "DEFLATE",
        "DEFRAG",
        "DELTA",
        "DELTA32K",
        "DESC",
        "DISABLE",
        "DISTINCT",
        "DO",
        "ELSE",
        "EMPTYASNULL",
        "ENABLE",
        "ENCODE",
        "ENCRYPT",
        "ENCRYPTION",
        "END",
        "EXPLICIT",
        "FALSE",
        "FOR",
        "FOREIGN",
        "FREEZE",
        "FULL",
        "GLOBALDICT256",
        "GLOBALDICT64K",
        "GRANT",
        "GZIP",
        "IDENTITY",
        "IGNORE",
        "ILIKE",
        "INITIALLY",
        "INTO",
        "LEADING",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "LUN",
        "LUNS",
        "LZO",
        "LZOP",
        "MINUS",
        "MOSTLY13",
        "MOSTLY32",
        "MOSTLY8",
        "NATURAL",
        "NEW",
        "NULLS",
        "OFF",
        "OFFLINE",
        "OFFSET",
        "OLD",
        "ON",
        "ONLY",
        "OPEN",
        "ORDER",
        "OVERLAPS",
        "PARALLEL",
        "PARTITION",
        "PERCENT",
        "PERMISSIONS",
        "PLACING",
        "PRIMARY",
        "RAW",
        "READRATIO",
        "RECOVER",
        "REFERENCES",
        "REJECTLOG",
        "RESORT",
        "RESTORE",
        "SESSION_USER",
        "SIMILAR",
        "SYSDATE",
        "SYSTEM",
        "TABLE",
        "TAG",
        "TDES",
        "TEXT255",
        "TEXT32K",
        "THEN",
        "TIMESTAMP",
        "TO",
        "TOP",
        "TRAILING",
        "TRUE",
        "TRUNCATECOLUMNS",
        "UNIQUE",
        "USER",
        "USING",
        "VERBOSE",
        "WALLET",
        "WHEN",
        "WITH",
        "WITHOUT",
        "PREDICATE",
        "COLUMNS",
        "COMPROWS",
        "COMPRESSION",
        "COPY",
        "FORMAT",
        "DELIMITER",
        "FIXEDWIDTH",
        "AVRO",
        "JSON",
        "ENCRYPTED",
        "BZIP2",
        "GZIP",
        "LZOP",
        "PARQUET",
        "ORC",
        "ACCEPTANYDATE",
        "ACCEPTINVCHARS",
        "BLANKSASNULL",
        "DATEFORMAT",
        "EMPTYASNULL",
        "ENCODING",
        "ESCAPE",
        "EXPLICIT_IDS",
        "FILLRECORD",
        "IGNOREBLANKLINES",
        "IGNOREHEADER",
        "NULL AS",
        "REMOVEQUOTES",
        "ROUNDEC",
        "TIMEFORMAT",
        "TRIMBLANKS",
        "TRUNCATECOLUMNS",
        "COMPROWS",
        "COMPUPDATE",
        "MAXERROR",
        "NOLOAD",
        "STATUPDATE",
        "MANIFEST",
        "REGION",
        "IAM_ROLE",
        "MASTER_SYMMETRIC_KEY",
        "SSH",
        "ACCEPTANYDATE",
        "ACCEPTINVCHARS",
        "ACCESS_KEY_ID",
        "SECRET_ACCESS_KEY",
        "AVRO",
        "BLANKSASNULL",
        "BZIP2",
        "COMPROWS",
        "COMPUPDATE",
        "CREDENTIALS",
        "DATEFORMAT",
        "DELIMITER",
        "EMPTYASNULL",
        "ENCODING",
        "ENCRYPTED",
        "ESCAPE",
        "EXPLICIT_IDS",
        "FILLRECORD",
        "FIXEDWIDTH",
        "FORMAT",
        "IAM_ROLE",
        "GZIP",
        "IGNOREBLANKLINES",
        "IGNOREHEADER",
        "JSON",
        "LZOP",
        "MANIFEST",
        "MASTER_SYMMETRIC_KEY",
        "MAXERROR",
        "NOLOAD",
        "NULL AS",
        "READRATIO",
        "REGION",
        "REMOVEQUOTES",
        "ROUNDEC",
        "SSH",
        "STATUPDATE",
        "TIMEFORMAT",
        "SESSION_TOKEN",
        "TRIMBLANKS",
        "TRUNCATECOLUMNS",
        "EXTERNAL",
        "DATA CATALOG",
        "HIVE METASTORE",
        "CATALOG_ROLE",
        "VACUUM",
        "COPY",
        "UNLOAD",
        "EVEN",
        "ALL",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "AFTER",
        "ALTER COLUMN",
        "ALTER TABLE",
        "DELETE FROM",
        "EXCEPT",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INSERT INTO",
        "INSERT",
        "INTERSECT",
        "TOP",
        "LIMIT",
        "MODIFY",
        "ORDER BY",
        "SELECT",
        "SET CURRENT SCHEMA",
        "SET SCHEMA",
        "SET",
        "UNION ALL",
        "UNION",
        "UPDATE",
        "VALUES",
        "WHERE",
        "VACUUM",
        "COPY",
        "UNLOAD",
        "ANALYZE",
        "ANALYSE",
        "DISTKEY",
        "SORTKEY",
        "COMPOUND",
        "INTERLEAVED",
        "FORMAT",
        "DELIMITER",
        "FIXEDWIDTH",
        "AVRO",
        "JSON",
        "ENCRYPTED",
        "BZIP2",
        "GZIP",
        "LZOP",
        "PARQUET",
        "ORC",
        "ACCEPTANYDATE",
        "ACCEPTINVCHARS",
        "BLANKSASNULL",
        "DATEFORMAT",
        "EMPTYASNULL",
        "ENCODING",
        "ESCAPE",
        "EXPLICIT_IDS",
        "FILLRECORD",
        "IGNOREBLANKLINES",
        "IGNOREHEADER",
        "NULL AS",
        "REMOVEQUOTES",
        "ROUNDEC",
        "TIMEFORMAT",
        "TRIMBLANKS",
        "TRUNCATECOLUMNS",
        "COMPROWS",
        "COMPUPDATE",
        "MAXERROR",
        "NOLOAD",
        "STATUPDATE",
        "MANIFEST",
        "REGION",
        "IAM_ROLE",
        "MASTER_SYMMETRIC_KEY",
        "SSH",
        "ACCEPTANYDATE",
        "ACCEPTINVCHARS",
        "ACCESS_KEY_ID",
        "SECRET_ACCESS_KEY",
        "AVRO",
        "BLANKSASNULL",
        "BZIP2",
        "COMPROWS",
        "COMPUPDATE",
        "CREDENTIALS",
        "DATEFORMAT",
        "DELIMITER",
        "EMPTYASNULL",
        "ENCODING",
        "ENCRYPTED",
        "ESCAPE",
        "EXPLICIT_IDS",
        "FILLRECORD",
        "FIXEDWIDTH",
        "FORMAT",
        "IAM_ROLE",
        "GZIP",
        "IGNOREBLANKLINES",
        "IGNOREHEADER",
        "JSON",
        "LZOP",
        "MANIFEST",
        "MASTER_SYMMETRIC_KEY",
        "MAXERROR",
        "NOLOAD",
        "NULL AS",
        "READRATIO",
        "REGION",
        "REMOVEQUOTES",
        "ROUNDEC",
        "SSH",
        "STATUPDATE",
        "TIMEFORMAT",
        "SESSION_TOKEN",
        "TRIMBLANKS",
        "TRUNCATECOLUMNS",
        "EXTERNAL",
        "DATA CATALOG",
        "HIVE METASTORE",
        "CATALOG_ROLE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "ELSE",
        "OR",
        "OUTER APPLY",
        "WHEN",
        "VACUUM",
        "COPY",
        "UNLOAD",
        "ANALYZE",
        "ANALYSE",
        "DISTKEY",
        "SORTKEY",
        "COMPOUND",
        "INTERLEAVED",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "FULL JOIN",
        "FULL OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::SingleQuote, StringType::Backtick],
        open_parens: &["("],
        close_parens: &[")"],
        indexed_placeholders: &['?'],
        named_placeholders: &['@', '#', '$'],
        line_comments: &["--"],
        special_word_chars: &[],
        extra_operators: &["|/", "||/", "<<", ">>", "!=", "||"],
        override_kind: OverrideKind::None,
    };
}

pub(crate) static REDSHIFT: Dialect = redshift::DIALECT;

mod postgres {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "ABORT",
        "ABSOLUTE",
        "ACCESS",
        "ACTION",
        "ADD",
        "ADMIN",
        "AFTER",
        "AGGREGATE",
        "ALL",
        "ALSO",
        "ALTER",
        "ALWAYS",
        "ANALYSE",
        "ANALYZE",
        "AND",
        "ANY",
        "ARRAY",
        "AS",
        "ASC",
        "ASSERTION",
        "ASSIGNMENT",
        "ASYMMETRIC",
        "AT",
        "ATTACH",
        "ATTRIBUTE",
        "AUTHORIZATION",
        "BACKWARD",
        "BEFORE",
        "BEGIN",
        "BETWEEN",
        "BIGINT",
        "BINARY",
        "BIT",
        "BOOLEAN",
        "BOTH",
        "BY",
        "CACHE",
        "CALL",
        "CALLED",
        "CASCADE",
        "CASCADED",
        "CASE",
        "CAST",
        "CATALOG",
        "CHAIN",
        "CHAR",
        "CHARACTER",
        "CHARACTERISTICS",
        "CHECK",
        "CHECKPOINT",
        "CLASS",
        "CLOSE",
        "CLUSTER",
        "COALESCE",
        "COLLATE",
        "COLLATION",
        "COLUMN",
        "COLUMNS",
        "COMMENT",
        "COMMENTS",
        "COMMIT",
        "COMMITTED",
        "CONCURRENTLY",
        "CONFIGURATION",
        "CONFLICT",
        "CONNECTION",
        "CONSTRAINT",
        "CONSTRAINTS",
        "CONTENT",
        "CONTINUE",
        "CONVERSION",
        "COPY",
        "COST",
        "CREATE",
        "CROSS",
        "CSV",
        "CUBE",
        "CURRENT",
        "CURRENT_CATALOG",
        "CURRENT_DATE",
        "CURRENT_ROLE",
        "CURRENT_SCHEMA",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_USER",
        "CURSOR",
        "CYCLE",
        "DATA",
        "DATABASE",
        "DAY",
        "DEALLOCATE",
        "DEC",
        "DECIMAL",
        "DECLARE",
        "DEFAULT",
        "DEFAULTS",
        "DEFERRABLE",
        "DEFERRED",
        "DEFINER",
        "DELETE",
        "DELIMITER",
        "DELIMITERS",
        "DEPENDS",
        "DESC",
        "DETACH",
        "DICTIONARY",
        "DISABLE",
        "DISCARD",
        "DISTINCT",
        "DO",
        "DOCUMENT",
        "DOMAIN",
        "DOUBLE",
        "DROP",
        "EACH",
        "ELSE",
        "ENABLE",
        "ENCODING",
        "ENCRYPTED",
        "END",
        "ENUM",
        "ESCAPE",
        "EVENT",
        "EXCEPT",
        "EXCLUDE",
        "EXCLUDING",
        "EXCLUSIVE",
        "EXECUTE",
        "EXISTS",
        "EXPLAIN",
        "EXPRESSION",
        "EXTENSION",
        "EXTERNAL",
        "EXTRACT",
        "FALSE",
        "FAMILY",
        "FETCH",
        "FILTER",
        "FIRST",
        "FLOAT",
        "FOLLOWING",
        "FOR",
        "FORCE",
        "FOREIGN",
        "FORWARD",
        "FREEZE",
        "FROM",
        "FULL",
        "FUNCTION",
        "FUNCTIONS",
        "GENERATED",
        "GLOBAL",
        "GRANT",
        "GRANTED",
        "GREATEST",
        "GROUP",
        "GROUPING",
        "GROUPS",
        "HANDLER",
        "HAVING",
        "HEADER",
        "HOLD",
        "HOUR",
        "IDENTITY",
        "IF",
        "ILIKE",
        "IMMEDIATE",
        "IMMUTABLE",
        "IMPLICIT",
        "IMPORT",
        "IN",
        "INCLUDE",
        "INCLUDING",
        "INCREMENT",
        "INDEX",
        "INDEXES",
        "INHERIT",
        "INHERITS",
        "INITIALLY",
        "INLINE",
        "INNER",
        "INOUT",
        "INPUT",
        "INSENSITIVE",
        "INSERT",
        "INSTEAD",
        "INT",
        "INTEGER",
        "INTERSECT",
        "INTERVAL",
        "INTO",
        "INVOKER",
        "IS",
        "ISNULL",
        "ISOLATION",
        "JOIN",
        "KEY",
        "LABEL",
        "LANGUAGE",
        "LARGE",
        "LAST",
        "LATERAL",
        "LEADING",
        "LEAKPROOF",
        "LEAST",
        "LEFT",
        "LEVEL",
        "LIKE",
        "LIMIT",
        "LISTEN",
        "LOAD",
        "LOCAL",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "LOCATION",
        "LOCK",
        "LOCKED",
        "LOGGED",
        "MAPPING",
        "MATCH",
        "MATERIALIZED",
        "MAXVALUE",
        "METHOD",
        "MINUTE",
        "MINVALUE",
        "MODE",
        "MONTH",
        "MOVE",
        "NAME",
        "NAMES",
        "NATIONAL",
        "NATURAL",
        "NCHAR",
        "NEW",
        "NEXT",
        "NFC",
        "NFD",
        "NFKC",
        "NFKD",
        "NO",
        "NONE",
        "NORMALIZE",
        "NORMALIZED",
        "NOT",
        "NOTHING",
        "NOTIFY",
        "NOTNULL",
        "NOWAIT",
        "NULL",
        "NULLIF",
        "NULLS",
        "NUMERIC",
        "OBJECT",
        "OF",
        "OFF",
        "OFFSET",
        "OIDS",
        "OLD",
        "ON",
        "ONLY",
        "OPERATOR",
        "OPTION",
        "OPTIONS",
        "OR",
        "ORDER",
        "ORDINALITY",
        "OTHERS",
        "OUT",
        "OUTER",
        "OVER",
        "OVERLAPS",
        "OVERLAY",
        "OVERRIDING",
        "OWNED",
        "OWNER",
        "PARALLEL",
        "PARSER",
        "PARTIAL",
        "PARTITION",
        "PASSING",
        "PASSWORD",
        "PLACING",
        "PLANS",
        "POLICY",
        "POSITION",
        "PRECEDING",
        "PRECISION",
        "PREPARE",
        "PREPARED",
        "PRESERVE",
        "PRIMARY",
        "PRIOR",
        "PRIVILEGES",
        "PROCEDURAL",
        "PROCEDURE",
        "PROCEDURES",
        "PROGRAM",
        "PUBLICATION",
        "QUOTE",
        "RANGE",
        "READ",
        "REAL",
        "REASSIGN",
        "RECHECK",
        "RECURSIVE",
        "REF",
        "REFERENCES",
        "REFERENCING",
        "REFRESH",
        "REINDEX",
        "RELATIVE",
        "RELEASE",
        "RENAME",
        "REPEATABLE",
        "REPLACE",
        "REPLICA",
        "RESET",
        "RESTART",
        "RESTRICT",
        "RETURNING",
        "RETURNS",
        "REVOKE",
        "RIGHT",
        "ROLE",
        "ROLLBACK",
        "ROLLUP",
        "ROUTINE",
        "ROUTINES",
        "ROW",
        "ROWS",
        "RULE",
        "SAVEPOINT",
        "SCHEMA",
        "SCHEMAS",
        "SCROLL",
        "SEARCH",
        "SECOND",
        "SECURITY",
        "SELECT",
        "SEQUENCE",
        "SEQUENCES",
        "SERIALIZABLE",
        "SERVER",
        "SESSION",
        "SESSION_USER",
        "SET",
        "SETOF",
        "SETS",
        "SHARE",
        "SHOW",
        "SIMILAR",
        "SIMPLE",
        "SKIP",
        "SMALLINT",
        "SNAPSHOT",
        "SOME",
        "SQL",
        "STABLE",
        "STANDALONE",
        "START",
        "STATEMENT",
        "STATISTICS",
        "STDIN",
        "STDOUT",
        "STORAGE",
        "STORED",
        "STRICT",
        "STRIP",
        "SUBSCRIPTION",
        "SUBSTRING",
        "SUPPORT",
        "SYMMETRIC",
        "SYSID",
        "SYSTEM",
        "TABLE",
        "TABLES",
        "TABLESAMPLE",
        "TABLESPACE",
        "TEMP",
        "TEMPLATE",
        "TEMPORARY",
        "TEXT",
        "THEN",
        "TIES",
        "TIME",
        "TIMESTAMP",
        "TO",
        "TRAILING",
        "TRANSACTION",
        "TRANSFORM",
        "TREAT",
        "TRIGGER",
        "TRIM",
        "TRUE",
        "TRUNCATE",
        "TRUSTED",
        "TYPE",
        "TYPES",
        "UESCAPE",
        "UNBOUNDED",
        "UNCOMMITTED",
        "UNENCRYPTED",
        "UNION",
        "UNIQUE",
        "UNKNOWN",
        "UNLISTEN",
        "UNLOGGED",
        "UNTIL",
        "UPDATE",
        "USER",
        "USING",
        "VACUUM",
        "VALID",
        "VALIDATE",
        "VALIDATOR",
        "VALUE",
        "VALUES",
        "VARCHAR",
        "VARIADIC",
        "VARYING",
        "VERBOSE",
        "VERSION",
        "VIEW",
        "VIEWS",
        "VOLATILE",
        "WHEN",
        "WHERE",
        "WHITESPACE",
        "WINDOW",
        "WITH",
        "WITHIN",
        "WITHOUT",
        "WORK",
        "WRAPPER",
        "WRITE",
        "XML",
        "XMLATTRIBUTES",
        "XMLCONCAT",
        "XMLELEMENT",
        "XMLEXISTS",
        "XMLFOREST",
        "XMLNAMESPACES",
        "XMLPARSE",
        "XMLPI",
        "XMLROOT",
        "XMLSERIALIZE",
        "XMLTABLE",
        "YEAR",
        "YES",
        "ZONE",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "AFTER",
        "ALTER COLUMN",
        "ALTER TABLE",
        "CASE",
        "DELETE FROM",
        "END",
        "EXCEPT",
        "FETCH FIRST",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INSERT INTO",
        "INSERT",
        "LIMIT",
        "ORDER BY",
        "SELECT",
        "SET CURRENT SCHEMA",
        "SET SCHEMA",
        "SET",
        "UPDATE",
        "VALUES",
        "WHERE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "ELSE",
        "OR",
        "WHEN",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "FULL JOIN",
        "FULL OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "INTERSECT",
        "INTERSECT ALL",
        "UNION",
        "UNION ALL",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::SingleQuote, StringType::UAndSingle, StringType::UAndDouble, StringType::Dollar],
        open_parens: &["(", "CASE"],
        close_parens: &[")", "END"],
        indexed_placeholders: &['$'],
        named_placeholders: &[':', '@'],
        line_comments: &["--"],
        special_word_chars: &['@', '$'],
        extra_operators: &["!=", "<<", ">>", "||/", "|/", "::", "->>", "->", "~~*", "~~", "!~~*", "!~~", "~*", "!~*", "!~", "!!"],
        override_kind: OverrideKind::None,
    };
}

pub(crate) static POSTGRES: Dialect = postgres::DIALECT;

mod plsql {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "A",
        "ACCESSIBLE",
        "AGENT",
        "AGGREGATE",
        "ALL",
        "ALTER",
        "ANY",
        "ARRAY",
        "AS",
        "ASC",
        "AT",
        "ATTRIBUTE",
        "AUTHID",
        "AVG",
        "BETWEEN",
        "BFILE_BASE",
        "BINARY_INTEGER",
        "BINARY",
        "BLOB_BASE",
        "BLOCK",
        "BODY",
        "BOOLEAN",
        "BOTH",
        "BOUND",
        "BREADTH",
        "BULK",
        "BY",
        "BYTE",
        "C",
        "CALL",
        "CALLING",
        "CASCADE",
        "CASE",
        "CHAR_BASE",
        "CHAR",
        "CHARACTER",
        "CHARSET",
        "CHARSETFORM",
        "CHARSETID",
        "CHECK",
        "CLOB_BASE",
        "CLONE",
        "CLOSE",
        "CLUSTER",
        "CLUSTERS",
        "COALESCE",
        "COLAUTH",
        "COLLECT",
        "COLUMNS",
        "COMMENT",
        "COMMIT",
        "COMMITTED",
        "COMPILED",
        "COMPRESS",
        "CONNECT",
        "CONSTANT",
        "CONSTRUCTOR",
        "CONTEXT",
        "CONTINUE",
        "CONVERT",
        "COUNT",
        "CRASH",
        "CREATE",
        "CREDENTIAL",
        "CURRENT",
        "CURRVAL",
        "CURSOR",
        "CUSTOMDATUM",
        "DANGLING",
        "DATA",
        "DATE_BASE",
        "DATE",
        "DAY",
        "DECIMAL",
        "DEFAULT",
        "DEFINE",
        "DELETE",
        "DEPTH",
        "DESC",
        "DETERMINISTIC",
        "DIRECTORY",
        "DISTINCT",
        "DO",
        "DOUBLE",
        "DROP",
        "DURATION",
        "ELEMENT",
        "ELSIF",
        "EMPTY",
        "END",
        "ESCAPE",
        "EXCEPTIONS",
        "EXCLUSIVE",
        "EXECUTE",
        "EXISTS",
        "EXIT",
        "EXTENDS",
        "EXTERNAL",
        "EXTRACT",
        "FALSE",
        "FETCH",
        "FINAL",
        "FIRST",
        "FIXED",
        "FLOAT",
        "FOR",
        "FORALL",
        "FORCE",
        "FROM",
        "FUNCTION",
        "GENERAL",
        "GOTO",
        "GRANT",
        "GROUP",
        "HASH",
        "HEAP",
        "HIDDEN",
        "HOUR",
        "IDENTIFIED",
        "IF",
        "IMMEDIATE",
        "IN",
        "INCLUDING",
        "INDEX",
        "INDEXES",
        "INDICATOR",
        "INDICES",
        "INFINITE",
        "INSTANTIABLE",
        "INT",
        "INTEGER",
        "INTERFACE",
        "INTERVAL",
        "INTO",
        "INVALIDATE",
        "IS",
        "ISOLATION",
        "JAVA",
        "LANGUAGE",
        "LARGE",
        "LEADING",
        "LENGTH",
        "LEVEL",
        "LIBRARY",
        "LIKE",
        "LIKE2",
        "LIKE4",
        "LIKEC",
        "LIMITED",
        "LOCAL",
        "LOCK",
        "LONG",
        "MAP",
        "MAX",
        "MAXLEN",
        "MEMBER",
        "MERGE",
        "MIN",
        "MINUTE",
        "MLSLABEL",
        "MOD",
        "MODE",
        "MONTH",
        "MULTISET",
        "NAME",
        "NAN",
        "NATIONAL",
        "NATIVE",
        "NATURAL",
        "NATURALN",
        "NCHAR",
        "NEW",
        "NEXTVAL",
        "NOCOMPRESS",
        "NOCOPY",
        "NOT",
        "NOWAIT",
        "NULL",
        "NULLIF",
        "NUMBER_BASE",
        "NUMBER",
        "OBJECT",
        "OCICOLL",
        "OCIDATE",
        "OCIDATETIME",
        "OCIDURATION",
        "OCIINTERVAL",
        "OCILOBLOCATOR",
        "OCINUMBER",
        "OCIRAW",
        "OCIREF",
        "OCIREFCURSOR",
        "OCIROWID",
        "OCISTRING",
        "OCITYPE",
        "OF",
        "OLD",
        "ON",
        "ONLY",
        "OPAQUE",
        "OPEN",
        "OPERATOR",
        "OPTION",
        "ORACLE",
        "ORADATA",
        "ORDER",
        "ORGANIZATION",
        "ORLANY",
        "ORLVARY",
        "OTHERS",
        "OUT",
        "OVERLAPS",
        "OVERRIDING",
        "PACKAGE",
        "PARALLEL_ENABLE",
        "PARAMETER",
        "PARAMETERS",
        "PARENT",
        "PARTITION",
        "PASCAL",
        "PCTFREE",
        "PIPE",
        "PIPELINED",
        "PLS_INTEGER",
        "PLUGGABLE",
        "POSITIVE",
        "POSITIVEN",
        "PRAGMA",
        "PRECISION",
        "PRIOR",
        "PRIVATE",
        "PROCEDURE",
        "PUBLIC",
        "RAISE",
        "RANGE",
        "RAW",
        "READ",
        "REAL",
        "RECORD",
        "REF",
        "REFERENCE",
        "RELEASE",
        "RELIES_ON",
        "REM",
        "REMAINDER",
        "RENAME",
        "RESOURCE",
        "RESULT_CACHE",
        "RESULT",
        "RETURN",
        "RETURNING",
        "REVERSE",
        "REVOKE",
        "ROLLBACK",
        "ROW",
        "ROWID",
        "ROWNUM",
        "ROWTYPE",
        "SAMPLE",
        "SAVE",
        "SAVEPOINT",
        "SB1",
        "SB2",
        "SB4",
        "SEARCH",
        "SECOND",
        "SEGMENT",
        "SELF",
        "SEPARATE",
        "SEQUENCE",
        "SERIALIZABLE",
        "SHARE",
        "SHORT",
        "SIZE_T",
        "SIZE",
        "SMALLINT",
        "SOME",
        "SPACE",
        "SPARSE",
        "SQL",
        "SQLCODE",
        "SQLDATA",
        "SQLERRM",
        "SQLNAME",
        "SQLSTATE",
        "STANDARD",
        "START",
        "STATIC",
        "STDDEV",
        "STORED",
        "STRING",
        "STRUCT",
        "STYLE",
        "SUBMULTISET",
        "SUBPARTITION",
        "SUBSTITUTABLE",
        "SUBTYPE",
        "SUCCESSFUL",
        "SUM",
        "SYNONYM",
        "SYSDATE",
        "TABAUTH",
        "TABLE",
        "TDO",
        "THE",
        "THEN",
        "TIME",
        "TIMESTAMP",
        "TIMEZONE_ABBR",
        "TIMEZONE_HOUR",
        "TIMEZONE_MINUTE",
        "TIMEZONE_REGION",
        "TO",
        "TRAILING",
        "TRANSACTION",
        "TRANSACTIONAL",
        "TRIGGER",
        "TRUE",
        "TRUSTED",
        "TYPE",
        "UB1",
        "UB2",
        "UB4",
        "UID",
        "UNDER",
        "UNIQUE",
        "UNPLUG",
        "UNSIGNED",
        "UNTRUSTED",
        "USE",
        "USER",
        "USING",
        "VALIDATE",
        "VALIST",
        "VALUE",
        "VARCHAR",
        "VARCHAR2",
        "VARIABLE",
        "VARIANCE",
        "VARRAY",
        "VARYING",
        "VIEW",
        "VIEWS",
        "VOID",
        "WHENEVER",
        "WHILE",
        "WITH",
        "WORK",
        "WRAPPED",
        "WRITE",
        "YEAR",
        "ZONE",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "ALTER COLUMN",
        "ALTER TABLE",
        "BEGIN",
        "CONNECT BY",
        "DECLARE",
        "DELETE FROM",
        "DELETE",
        "END",
        "EXCEPT",
        "EXCEPTION",
        "FETCH FIRST",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INSERT INTO",
        "INSERT",
        "LIMIT",
        "LOOP",
        "MODIFY",
        "ORDER BY",
        "SELECT",
        "SET CURRENT SCHEMA",
        "SET SCHEMA",
        "SET",
        "START WITH",
        "UPDATE",
        "VALUES",
        "WHERE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "CROSS APPLY",
        "ELSE",
        "END",
        "OR",
        "OUTER APPLY",
        "WHEN",
        "XOR",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "FULL JOIN",
        "FULL OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "INTERSECT",
        "INTERSECT ALL",
        "MINUS",
        "UNION",
        "UNION ALL",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::NSingle, StringType::SingleQuote, StringType::Backtick],
        open_parens: &["(", "CASE"],
        close_parens: &[")", "END"],
        indexed_placeholders: &['?'],
        named_placeholders: &[':'],
        line_comments: &["--"],
        special_word_chars: &['_', '$', '#', '.', '@'],
        extra_operators: &["||", "**", "!=", ":="],
        override_kind: OverrideKind::PlSql,
    };
}

pub(crate) static PLSQL: Dialect = plsql::DIALECT;

mod n1ql {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "ALL",
        "ALTER",
        "ANALYZE",
        "AND",
        "ANY",
        "ARRAY",
        "AS",
        "ASC",
        "BEGIN",
        "BETWEEN",
        "BINARY",
        "BOOLEAN",
        "BREAK",
        "BUCKET",
        "BUILD",
        "BY",
        "CALL",
        "CASE",
        "CAST",
        "CLUSTER",
        "COLLATE",
        "COLLECTION",
        "COMMIT",
        "CONNECT",
        "CONTINUE",
        "CORRELATE",
        "COVER",
        "CREATE",
        "DATABASE",
        "DATASET",
        "DATASTORE",
        "DECLARE",
        "DECREMENT",
        "DELETE",
        "DERIVED",
        "DESC",
        "DESCRIBE",
        "DISTINCT",
        "DO",
        "DROP",
        "EACH",
        "ELEMENT",
        "ELSE",
        "END",
        "EVERY",
        "EXCEPT",
        "EXCLUDE",
        "EXECUTE",
        "EXISTS",
        "EXPLAIN",
        "FALSE",
        "FETCH",
        "FIRST",
        "FLATTEN",
        "FOR",
        "FORCE",
        "FROM",
        "FUNCTION",
        "GRANT",
        "GROUP",
        "GSI",
        "HAVING",
        "IF",
        "IGNORE",
        "ILIKE",
        "IN",
        "INCLUDE",
        "INCREMENT",
        "INDEX",
        "INFER",
        "INLINE",
        "INNER",
        "INSERT",
        "INTERSECT",
        "INTO",
        "IS",
        "JOIN",
        "KEY",
        "KEYS",
        "KEYSPACE",
        "KNOWN",
        "LAST",
        "LEFT",
        "LET",
        "LETTING",
        "LIKE",
        "LIMIT",
        "LSM",
        "MAP",
        "MAPPING",
        "MATCHED",
        "MATERIALIZED",
        "MERGE",
        "MISSING",
        "NAMESPACE",
        "NEST",
        "NOT",
        "NULL",
        "NUMBER",
        "OBJECT",
        "OFFSET",
        "ON",
        "OPTION",
        "OR",
        "ORDER",
        "OUTER",
        "OVER",
        "PARSE",
        "PARTITION",
        "PASSWORD",
        "PATH",
        "POOL",
        "PREPARE",
        "PRIMARY",
        "PRIVATE",
        "PRIVILEGE",
        "PROCEDURE",
        "PUBLIC",
        "RAW",
        "REALM",
        "REDUCE",
        "RENAME",
        "RETURN",
        "RETURNING",
        "REVOKE",
        "RIGHT",
        "ROLE",
        "ROLLBACK",
        "SATISFIES",
        "SCHEMA",
        "SELECT",
        "SELF",
        "SEMI",
        "SET",
        "SHOW",
        "SOME",
        "START",
        "STATISTICS",
        "STRING",
        "SYSTEM",
        "THEN",
        "TO",
        "TRANSACTION",
        "TRIGGER",
        "TRUE",
        "TRUNCATE",
        "UNDER",
        "UNION",
        "UNIQUE",
        "UNKNOWN",
        "UNNEST",
        "UNSET",
        "UPDATE",
        "UPSERT",
        "USE",
        "USER",
        "USING",
        "VALIDATE",
        "VALUE",
        "VALUED",
        "VALUES",
        "VIA",
        "VIEW",
        "WHEN",
        "WHERE",
        "WHILE",
        "WITH",
        "WITHIN",
        "WORK",
        "XOR",
    ];
    pub(crate) const TOP: &[&str] = &[
        "DELETE FROM",
        "EXCEPT ALL",
        "EXCEPT",
        "EXPLAIN DELETE FROM",
        "EXPLAIN UPDATE",
        "EXPLAIN UPSERT",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INFER",
        "INSERT INTO",
        "LET",
        "LIMIT",
        "MERGE",
        "NEST",
        "ORDER BY",
        "PREPARE",
        "SELECT",
        "SET CURRENT SCHEMA",
        "SET SCHEMA",
        "SET",
        "UNNEST",
        "UPDATE",
        "UPSERT",
        "USE KEYS",
        "VALUES",
        "WHERE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "OR",
        "XOR",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "INTERSECT",
        "INTERSECT ALL",
        "MINUS",
        "UNION",
        "UNION ALL",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::SingleQuote, StringType::Backtick],
        open_parens: &["(", "[", "{"],
        close_parens: &[")", "]", "}"],
        indexed_placeholders: &[],
        named_placeholders: &['$'],
        line_comments: &["#", "--"],
        special_word_chars: &[],
        extra_operators: &["==", "!="],
        override_kind: OverrideKind::None,
    };
}

pub(crate) static N1QL: Dialect = n1ql::DIALECT;

mod mysql {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "ACCESSIBLE",
        "ADD",
        "ALL",
        "ALTER",
        "ANALYZE",
        "AND",
        "AS",
        "ASC",
        "ASENSITIVE",
        "BEFORE",
        "BETWEEN",
        "BIGINT",
        "BINARY",
        "BLOB",
        "BOTH",
        "BY",
        "CALL",
        "CASCADE",
        "CASE",
        "CHANGE",
        "CHAR",
        "CHARACTER",
        "CHECK",
        "COLLATE",
        "COLUMN",
        "CONDITION",
        "CONSTRAINT",
        "CONTINUE",
        "CONVERT",
        "CREATE",
        "CROSS",
        "CUBE",
        "CUME_DIST",
        "CURRENT_DATE",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_USER",
        "CURSOR",
        "DATABASE",
        "DATABASES",
        "DAY_HOUR",
        "DAY_MICROSECOND",
        "DAY_MINUTE",
        "DAY_SECOND",
        "DEC",
        "DECIMAL",
        "DECLARE",
        "DEFAULT",
        "DELAYED",
        "DELETE",
        "DENSE_RANK",
        "DESC",
        "DESCRIBE",
        "DETERMINISTIC",
        "DISTINCT",
        "DISTINCTROW",
        "DIV",
        "DOUBLE",
        "DROP",
        "DUAL",
        "EACH",
        "ELSE",
        "ELSEIF",
        "EMPTY",
        "ENCLOSED",
        "ESCAPED",
        "EXCEPT",
        "EXISTS",
        "EXIT",
        "EXPLAIN",
        "FALSE",
        "FETCH",
        "FIRST_VALUE",
        "FLOAT",
        "FLOAT4",
        "FLOAT8",
        "FOR",
        "FORCE",
        "FOREIGN",
        "FROM",
        "FULLTEXT",
        "FUNCTION",
        "GENERATED",
        "GET",
        "GRANT",
        "GROUP",
        "GROUPING",
        "GROUPS",
        "HAVING",
        "HIGH_PRIORITY",
        "HOUR_MICROSECOND",
        "HOUR_MINUTE",
        "HOUR_SECOND",
        "IF",
        "IGNORE",
        "IN",
        "INDEX",
        "INFILE",
        "INNER",
        "INOUT",
        "INSENSITIVE",
        "INSERT",
        "INT",
        "INT1",
        "INT2",
        "INT3",
        "INT4",
        "INT8",
        "INTEGER",
        "INTERVAL",
        "INTO",
        "IO_AFTER_GTIDS",
        "IO_BEFORE_GTIDS",
        "IS",
        "ITERATE",
        "JOIN",
        "JSON_TABLE",
        "KEY",
        "KEYS",
        "KILL",
        "LAG",
        "LAST_VALUE",
        "LATERAL",
        "LEAD",
        "LEADING",
        "LEAVE",
        "LEFT",
        "LIKE",
        "LIMIT",
        "LINEAR",
        "LINES",
        "LOAD",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "LOCK",
        "LONG",
        "LONGBLOB",
        "LONGTEXT",
        "LOOP",
        "LOW_PRIORITY",
        "MASTER_BIND",
        "MASTER_SSL_VERIFY_SERVER_CERT",
        "MATCH",
        "MAXVALUE",
        "MEDIUMBLOB",
        "MEDIUMINT",
        "MEDIUMTEXT",
        "MIDDLEINT",
        "MINUTE_MICROSECOND",
        "MINUTE_SECOND",
        "MOD",
        "MODIFIES",
        "NATURAL",
        "NOT",
        "NO_WRITE_TO_BINLOG",
        "NTH_VALUE",
        "NTILE",
        "NULL",
        "NUMERIC",
        "OF",
        "ON",
        "OPTIMIZE",
        "OPTIMIZER_COSTS",
        "OPTION",
        "OPTIONALLY",
        "OR",
        "ORDER",
        "OUT",
        "OUTER",
        "OUTFILE",
        "OVER",
        "PARTITION",
        "PERCENT_RANK",
        "PRECISION",
        "PRIMARY",
        "PROCEDURE",
        "PURGE",
        "RANGE",
        "RANK",
        "READ",
        "READS",
        "READ_WRITE",
        "REAL",
        "RECURSIVE",
        "REFERENCES",
        "REGEXP",
        "RELEASE",
        "RENAME",
        "REPEAT",
        "REPLACE",
        "REQUIRE",
        "RESIGNAL",
        "RESTRICT",
        "RETURN",
        "REVOKE",
        "RIGHT",
        "RLIKE",
        "ROW",
        "ROWS",
        "ROW_NUMBER",
        "SCHEMA",
        "SCHEMAS",
        "SECOND_MICROSECOND",
        "SELECT",
        "SENSITIVE",
        "SEPARATOR",
        "SET",
        "SHOW",
        "SIGNAL",
        "SMALLINT",
        "SPATIAL",
        "SPECIFIC",
        "SQL",
        "SQLEXCEPTION",
        "SQLSTATE",
        "SQLWARNING",
        "SQL_BIG_RESULT",
        "SQL_CALC_FOUND_ROWS",
        "SQL_SMALL_RESULT",
        "SSL",
        "STARTING",
        "STORED",
        "STRAIGHT_JOIN",
        "SYSTEM",
        "TABLE",
        "TERMINATED",
        "THEN",
        "TINYBLOB",
        "TINYINT",
        "TINYTEXT",
        "TO",
        "TRAILING",
        "TRIGGER",
        "TRUE",
        "UNDO",
        "UNION",
        "UNIQUE",
        "UNLOCK",
        "UNSIGNED",
        "UPDATE",
        "USAGE",
        "USE",
        "USING",
        "UTC_DATE",
        "UTC_TIME",
        "UTC_TIMESTAMP",
        "VALUES",
        "VARBINARY",
        "VARCHAR",
        "VARCHARACTER",
        "VARYING",
        "VIRTUAL",
        "WHEN",
        "WHERE",
        "WHILE",
        "WINDOW",
        "WITH",
        "WRITE",
        "XOR",
        "YEAR_MONTH",
        "ZEROFILL",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "ALTER COLUMN",
        "ALTER TABLE",
        "DELETE FROM",
        "EXCEPT",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INSERT INTO",
        "INSERT",
        "LIMIT",
        "ORDER BY",
        "SELECT",
        "SET",
        "UPDATE",
        "VALUES",
        "WHERE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "ELSE",
        "OR",
        "WHEN",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
        "STRAIGHT_JOIN",
        "NATURAL LEFT JOIN",
        "NATURAL LEFT OUTER JOIN",
        "NATURAL RIGHT JOIN",
        "NATURAL RIGHT OUTER JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "INTERSECT",
        "INTERSECT ALL",
        "UNION",
        "UNION ALL",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::SingleQuote, StringType::Backtick],
        open_parens: &["(", "CASE"],
        close_parens: &[")", "END"],
        indexed_placeholders: &['?'],
        named_placeholders: &[],
        line_comments: &["#", "--"],
        special_word_chars: &['#', '@', '$'],
        extra_operators: &[":=", "<<", ">>", "!=", "<>", "<=>", "&&", "||", "->", "->>"],
        override_kind: OverrideKind::None,
    };
}

pub(crate) static MYSQL: Dialect = mysql::DIALECT;

mod mariadb {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "ACCESSIBLE",
        "ADD",
        "ALL",
        "ALTER",
        "ANALYZE",
        "AND",
        "AS",
        "ASC",
        "ASENSITIVE",
        "BEFORE",
        "BETWEEN",
        "BIGINT",
        "BINARY",
        "BLOB",
        "BOTH",
        "BY",
        "CALL",
        "CASCADE",
        "CASE",
        "CHANGE",
        "CHAR",
        "CHARACTER",
        "CHECK",
        "COLLATE",
        "COLUMN",
        "CONDITION",
        "CONSTRAINT",
        "CONTINUE",
        "CONVERT",
        "CREATE",
        "CROSS",
        "CURRENT_DATE",
        "CURRENT_ROLE",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_USER",
        "CURSOR",
        "DATABASE",
        "DATABASES",
        "DAY_HOUR",
        "DAY_MICROSECOND",
        "DAY_MINUTE",
        "DAY_SECOND",
        "DEC",
        "DECIMAL",
        "DECLARE",
        "DEFAULT",
        "DELAYED",
        "DELETE",
        "DESC",
        "DESCRIBE",
        "DETERMINISTIC",
        "DISTINCT",
        "DISTINCTROW",
        "DIV",
        "DO_DOMAIN_IDS",
        "DOUBLE",
        "DROP",
        "DUAL",
        "EACH",
        "ELSE",
        "ELSEIF",
        "ENCLOSED",
        "ESCAPED",
        "EXCEPT",
        "EXISTS",
        "EXIT",
        "EXPLAIN",
        "FALSE",
        "FETCH",
        "FLOAT",
        "FLOAT4",
        "FLOAT8",
        "FOR",
        "FORCE",
        "FOREIGN",
        "FROM",
        "FULLTEXT",
        "GENERAL",
        "GRANT",
        "GROUP",
        "HAVING",
        "HIGH_PRIORITY",
        "HOUR_MICROSECOND",
        "HOUR_MINUTE",
        "HOUR_SECOND",
        "IF",
        "IGNORE",
        "IGNORE_DOMAIN_IDS",
        "IGNORE_SERVER_IDS",
        "IN",
        "INDEX",
        "INFILE",
        "INNER",
        "INOUT",
        "INSENSITIVE",
        "INSERT",
        "INT",
        "INT1",
        "INT2",
        "INT3",
        "INT4",
        "INT8",
        "INTEGER",
        "INTERSECT",
        "INTERVAL",
        "INTO",
        "IS",
        "ITERATE",
        "JOIN",
        "KEY",
        "KEYS",
        "KILL",
        "LEADING",
        "LEAVE",
        "LEFT",
        "LIKE",
        "LIMIT",
        "LINEAR",
        "LINES",
        "LOAD",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "LOCK",
        "LONG",
        "LONGBLOB",
        "LONGTEXT",
        "LOOP",
        "LOW_PRIORITY",
        "MASTER_HEARTBEAT_PERIOD",
        "MASTER_SSL_VERIFY_SERVER_CERT",
        "MATCH",
        "MAXVALUE",
        "MEDIUMBLOB",
        "MEDIUMINT",
        "MEDIUMTEXT",
        "MIDDLEINT",
        "MINUTE_MICROSECOND",
        "MINUTE_SECOND",
        "MOD",
        "MODIFIES",
        "NATURAL",
        "NOT",
        "NO_WRITE_TO_BINLOG",
        "NULL",
        "NUMERIC",
        "ON",
        "OPTIMIZE",
        "OPTION",
        "OPTIONALLY",
        "OR",
        "ORDER",
        "OUT",
        "OUTER",
        "OUTFILE",
        "OVER",
        "PAGE_CHECKSUM",
        "PARSE_VCOL_EXPR",
        "PARTITION",
        "POSITION",
        "PRECISION",
        "PRIMARY",
        "PROCEDURE",
        "PURGE",
        "RANGE",
        "READ",
        "READS",
        "READ_WRITE",
        "REAL",
        "RECURSIVE",
        "REF_SYSTEM_ID",
        "REFERENCES",
        "REGEXP",
        "RELEASE",
        "RENAME",
        "REPEAT",
        "REPLACE",
        "REQUIRE",
        "RESIGNAL",
        "RESTRICT",
        "RETURN",
        "RETURNING",
        "REVOKE",
        "RIGHT",
        "RLIKE",
        "ROWS",
        "SCHEMA",
        "SCHEMAS",
        "SECOND_MICROSECOND",
        "SELECT",
        "SENSITIVE",
        "SEPARATOR",
        "SET",
        "SHOW",
        "SIGNAL",
        "SLOW",
        "SMALLINT",
        "SPATIAL",
        "SPECIFIC",
        "SQL",
        "SQLEXCEPTION",
        "SQLSTATE",
        "SQLWARNING",
        "SQL_BIG_RESULT",
        "SQL_CALC_FOUND_ROWS",
        "SQL_SMALL_RESULT",
        "SSL",
        "STARTING",
        "STATS_AUTO_RECALC",
        "STATS_PERSISTENT",
        "STATS_SAMPLE_PAGES",
        "STRAIGHT_JOIN",
        "TABLE",
        "TERMINATED",
        "THEN",
        "TINYBLOB",
        "TINYINT",
        "TINYTEXT",
        "TO",
        "TRAILING",
        "TRIGGER",
        "TRUE",
        "UNDO",
        "UNION",
        "UNIQUE",
        "UNLOCK",
        "UNSIGNED",
        "UPDATE",
        "USAGE",
        "USE",
        "USING",
        "UTC_DATE",
        "UTC_TIME",
        "UTC_TIMESTAMP",
        "VALUES",
        "VARBINARY",
        "VARCHAR",
        "VARCHARACTER",
        "VARYING",
        "WHEN",
        "WHERE",
        "WHILE",
        "WINDOW",
        "WITH",
        "WRITE",
        "XOR",
        "YEAR_MONTH",
        "ZEROFILL",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "ALTER COLUMN",
        "ALTER TABLE",
        "DELETE FROM",
        "EXCEPT",
        "FROM",
        "GROUP BY",
        "HAVING",
        "INSERT INTO",
        "INSERT",
        "LIMIT",
        "ORDER BY",
        "SELECT",
        "SET",
        "UPDATE",
        "VALUES",
        "WHERE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "ELSE",
        "OR",
        "WHEN",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
        "STRAIGHT_JOIN",
        "NATURAL LEFT JOIN",
        "NATURAL LEFT OUTER JOIN",
        "NATURAL RIGHT JOIN",
        "NATURAL RIGHT OUTER JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "INTERSECT",
        "INTERSECT ALL",
        "UNION",
        "UNION ALL",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::SingleQuote, StringType::Backtick],
        open_parens: &["(", "CASE"],
        close_parens: &[")", "END"],
        indexed_placeholders: &['?'],
        named_placeholders: &[],
        line_comments: &["#", "--"],
        special_word_chars: &['#', '@', '$'],
        extra_operators: &[":=", "<<", ">>", "!=", "<>", "<=>", "&&", "||"],
        override_kind: OverrideKind::None,
    };
}

pub(crate) static MARIADB: Dialect = mariadb::DIALECT;

mod db2 {
    use super::*;

    pub(crate) const RESERVED: &[&str] = &[
        "ABS",
        "ACTIVATE",
        "ALIAS",
        "ALL",
        "ALLOCATE",
        "ALLOW",
        "ALTER",
        "ANY",
        "ARE",
        "ARRAY",
        "AS",
        "ASC",
        "ASENSITIVE",
        "ASSOCIATE",
        "ASUTIME",
        "ASYMMETRIC",
        "AT",
        "ATOMIC",
        "ATTRIBUTES",
        "AUDIT",
        "AUTHORIZATION",
        "AUX",
        "AUXILIARY",
        "AVG",
        "BEFORE",
        "BEGIN",
        "BETWEEN",
        "BIGINT",
        "BINARY",
        "BLOB",
        "BOOLEAN",
        "BOTH",
        "BUFFERPOOL",
        "BY",
        "CACHE",
        "CALL",
        "CALLED",
        "CAPTURE",
        "CARDINALITY",
        "CASCADED",
        "CASE",
        "CAST",
        "CCSID",
        "CEIL",
        "CEILING",
        "CHAR",
        "CHARACTER",
        "CHARACTER_LENGTH",
        "CHAR_LENGTH",
        "CHECK",
        "CLOB",
        "CLONE",
        "CLOSE",
        "CLUSTER",
        "COALESCE",
        "COLLATE",
        "COLLECT",
        "COLLECTION",
        "COLLID",
        "COLUMN",
        "COMMENT",
        "COMMIT",
        "CONCAT",
        "CONDITION",
        "CONNECT",
        "CONNECTION",
        "CONSTRAINT",
        "CONTAINS",
        "CONTINUE",
        "CONVERT",
        "CORR",
        "CORRESPONDING",
        "COUNT",
        "COUNT_BIG",
        "COVAR_POP",
        "COVAR_SAMP",
        "CREATE",
        "CROSS",
        "CUBE",
        "CUME_DIST",
        "CURRENT",
        "CURRENT_DATE",
        "CURRENT_DEFAULT_TRANSFORM_GROUP",
        "CURRENT_LC_CTYPE",
        "CURRENT_PATH",
        "CURRENT_ROLE",
        "CURRENT_SCHEMA",
        "CURRENT_SERVER",
        "CURRENT_TIME",
        "CURRENT_TIMESTAMP",
        "CURRENT_TIMEZONE",
        "CURRENT_TRANSFORM_GROUP_FOR_TYPE",
        "CURRENT_USER",
        "CURSOR",
        "CYCLE",
        "DATA",
        "DATABASE",
        "DATAPARTITIONNAME",
        "DATAPARTITIONNUM",
        "DATE",
        "DAY",
        "DAYS",
        "DB2GENERAL",
        "DB2GENRL",
        "DB2SQL",
        "DBINFO",
        "DBPARTITIONNAME",
        "DBPARTITIONNUM",
        "DEALLOCATE",
        "DEC",
        "DECIMAL",
        "DECLARE",
        "DEFAULT",
        "DEFAULTS",
        "DEFINITION",
        "DELETE",
        "DENSERANK",
        "DENSE_RANK",
        "DEREF",
        "DESCRIBE",
        "DESCRIPTOR",
        "DETERMINISTIC",
        "DIAGNOSTICS",
        "DISABLE",
        "DISALLOW",
        "DISCONNECT",
        "DISTINCT",
        "DO",
        "DOCUMENT",
        "DOUBLE",
        "DROP",
        "DSSIZE",
        "DYNAMIC",
        "EACH",
        "EDITPROC",
        "ELEMENT",
        "ELSE",
        "ELSEIF",
        "ENABLE",
        "ENCODING",
        "ENCRYPTION",
        "END",
        "END-EXEC",
        "ENDING",
        "ERASE",
        "ESCAPE",
        "EVERY",
        "EXCEPTION",
        "EXCLUDING",
        "EXCLUSIVE",
        "EXEC",
        "EXECUTE",
        "EXISTS",
        "EXIT",
        "EXP",
        "EXPLAIN",
        "EXTENDED",
        "EXTERNAL",
        "EXTRACT",
        "FALSE",
        "FENCED",
        "FETCH",
        "FIELDPROC",
        "FILE",
        "FILTER",
        "FINAL",
        "FIRST",
        "FLOAT",
        "FLOOR",
        "FOR",
        "FOREIGN",
        "FREE",
        "FULL",
        "FUNCTION",
        "FUSION",
        "GENERAL",
        "GENERATED",
        "GET",
        "GLOBAL",
        "GOTO",
        "GRANT",
        "GRAPHIC",
        "GROUP",
        "GROUPING",
        "HANDLER",
        "HASH",
        "HASHED_VALUE",
        "HINT",
        "HOLD",
        "HOUR",
        "HOURS",
        "IDENTITY",
        "IF",
        "IMMEDIATE",
        "IN",
        "INCLUDING",
        "INCLUSIVE",
        "INCREMENT",
        "INDEX",
        "INDICATOR",
        "INDICATORS",
        "INF",
        "INFINITY",
        "INHERIT",
        "INNER",
        "INOUT",
        "INSENSITIVE",
        "INSERT",
        "INT",
        "INTEGER",
        "INTEGRITY",
        "INTERSECTION",
        "INTERVAL",
        "INTO",
        "IS",
        "ISOBID",
        "ISOLATION",
        "ITERATE",
        "JAR",
        "JAVA",
        "KEEP",
        "KEY",
        "LABEL",
        "LANGUAGE",
        "LARGE",
        "LATERAL",
        "LC_CTYPE",
        "LEADING",
        "LEAVE",
        "LEFT",
        "LIKE",
        "LINKTYPE",
        "LN",
        "LOCAL",
        "LOCALDATE",
        "LOCALE",
        "LOCALTIME",
        "LOCALTIMESTAMP",
        "LOCATOR",
        "LOCATORS",
        "LOCK",
        "LOCKMAX",
        "LOCKSIZE",
        "LONG",
        "LOOP",
        "LOWER",
        "MAINTAINED",
        "MATCH",
        "MATERIALIZED",
        "MAX",
        "MAXVALUE",
        "MEMBER",
        "MERGE",
        "METHOD",
        "MICROSECOND",
        "MICROSECONDS",
        "MIN",
        "MINUTE",
        "MINUTES",
        "MINVALUE",
        "MOD",
        "MODE",
        "MODIFIES",
        "MODULE",
        "MONTH",
        "MONTHS",
        "MULTISET",
        "NAN",
        "NATIONAL",
        "NATURAL",
        "NCHAR",
        "NCLOB",
        "NEW",
        "NEW_TABLE",
        "NEXTVAL",
        "NO",
        "NOCACHE",
        "NOCYCLE",
        "NODENAME",
        "NODENUMBER",
        "NOMAXVALUE",
        "NOMINVALUE",
        "NONE",
        "NOORDER",
        "NORMALIZE",
        "NORMALIZED",
        "NOT",
        "NULL",
        "NULLIF",
        "NULLS",
        "NUMERIC",
        "NUMPARTS",
        "OBID",
        "OCTET_LENGTH",
        "OF",
        "OFFSET",
        "OLD",
        "OLD_TABLE",
        "ON",
        "ONLY",
        "OPEN",
        "OPTIMIZATION",
        "OPTIMIZE",
        "OPTION",
        "ORDER",
        "OUT",
        "OUTER",
        "OVER",
        "OVERLAPS",
        "OVERLAY",
        "OVERRIDING",
        "PACKAGE",
        "PADDED",
        "PAGESIZE",
        "PARAMETER",
        "PART",
        "PARTITION",
        "PARTITIONED",
        "PARTITIONING",
        "PARTITIONS",
        "PASSWORD",
        "PATH",
        "PERCENTILE_CONT",
        "PERCENTILE_DISC",
        "PERCENT_RANK",
        "PIECESIZE",
        "PLAN",
        "POSITION",
        "POWER",
        "PRECISION",
        "PREPARE",
        "PREVVAL",
        "PRIMARY",
        "PRIQTY",
        "PRIVILEGES",
        "PROCEDURE",
        "PROGRAM",
        "PSID",
        "PUBLIC",
        "QUERY",
        "QUERYNO",
        "RANGE",
        "RANK",
        "READ",
        "READS",
        "REAL",
        "RECOVERY",
        "RECURSIVE",
        "REF",
        "REFERENCES",
        "REFERENCING",
        "REFRESH",
        "REGR_AVGX",
        "REGR_AVGY",
        "REGR_COUNT",
        "REGR_INTERCEPT",
        "REGR_R2",
        "REGR_SLOPE",
        "REGR_SXX",
        "REGR_SXY",
        "REGR_SYY",
        "RELEASE",
        "RENAME",
        "REPEAT",
        "RESET",
        "RESIGNAL",
        "RESTART",
        "RESTRICT",
        "RESULT",
        "RESULT_SET_LOCATOR",
        "RETURN",
        "RETURNS",
        "REVOKE",
        "RIGHT",
        "ROLE",
        "ROLLBACK",
        "ROLLUP",
        "ROUND_CEILING",
        "ROUND_DOWN",
        "ROUND_FLOOR",
        "ROUND_HALF_DOWN",
        "ROUND_HALF_EVEN",
        "ROUND_HALF_UP",
        "ROUND_UP",
        "ROUTINE",
        "ROW",
        "ROWNUMBER",
        "ROWS",
        "ROWSET",
        "ROW_NUMBER",
        "RRN",
        "RUN",
        "SAVEPOINT",
        "SCHEMA",
        "SCOPE",
        "SCRATCHPAD",
        "SCROLL",
        "SEARCH",
        "SECOND",
        "SECONDS",
        "SECQTY",
        "SECURITY",
        "SENSITIVE",
        "SEQUENCE",
        "SESSION",
        "SESSION_USER",
        "SIGNAL",
        "SIMILAR",
        "SIMPLE",
        "SMALLINT",
        "SNAN",
        "SOME",
        "SOURCE",
        "SPECIFIC",
        "SPECIFICTYPE",
        "SQL",
        "SQLEXCEPTION",
        "SQLID",
        "SQLSTATE",
        "SQLWARNING",
        "SQRT",
        "STACKED",
        "STANDARD",
        "START",
        "STARTING",
        "STATEMENT",
        "STATIC",
        "STATMENT",
        "STAY",
        "STDDEV_POP",
        "STDDEV_SAMP",
        "STOGROUP",
        "STORES",
        "STYLE",
        "SUBMULTISET",
        "SUBSTRING",
        "SUM",
        "SUMMARY",
        "SYMMETRIC",
        "SYNONYM",
        "SYSFUN",
        "SYSIBM",
        "SYSPROC",
        "SYSTEM",
        "SYSTEM_USER",
        "TABLE",
        "TABLESAMPLE",
        "TABLESPACE",
        "THEN",
        "TIME",
        "TIMESTAMP",
        "TIMEZONE_HOUR",
        "TIMEZONE_MINUTE",
        "TO",
        "TRAILING",
        "TRANSACTION",
        "TRANSLATE",
        "TRANSLATION",
        "TREAT",
        "TRIGGER",
        "TRIM",
        "TRUE",
        "TRUNCATE",
        "TYPE",
        "UESCAPE",
        "UNDO",
        "UNIQUE",
        "UNKNOWN",
        "UNNEST",
        "UNTIL",
        "UPPER",
        "USAGE",
        "USER",
        "USING",
        "VALIDPROC",
        "VALUE",
        "VARCHAR",
        "VARIABLE",
        "VARIANT",
        "VARYING",
        "VAR_POP",
        "VAR_SAMP",
        "VCAT",
        "VERSION",
        "VIEW",
        "VOLATILE",
        "VOLUMES",
        "WHEN",
        "WHENEVER",
        "WHILE",
        "WIDTH_BUCKET",
        "WINDOW",
        "WITH",
        "WITHIN",
        "WITHOUT",
        "WLM",
        "WRITE",
        "XMLELEMENT",
        "XMLEXISTS",
        "XMLNAMESPACES",
        "YEAR",
        "YEARS",
    ];
    pub(crate) const TOP: &[&str] = &[
        "ADD",
        "AFTER",
        "ALTER COLUMN",
        "ALTER TABLE",
        "DELETE FROM",
        "EXCEPT",
        "FETCH FIRST",
        "FROM",
        "GROUP BY",
        "GO",
        "HAVING",
        "INSERT INTO",
        "INTERSECT",
        "LIMIT",
        "ORDER BY",
        "SELECT",
        "SET CURRENT SCHEMA",
        "SET SCHEMA",
        "SET",
        "UPDATE",
        "VALUES",
        "WHERE",
    ];
    pub(crate) const NEWLINE: &[&str] = &[
        "AND",
        "OR",
        "JOIN",
        "INNER JOIN",
        "LEFT JOIN",
        "LEFT OUTER JOIN",
        "RIGHT JOIN",
        "RIGHT OUTER JOIN",
        "FULL JOIN",
        "FULL OUTER JOIN",
        "CROSS JOIN",
        "NATURAL JOIN",
    ];
    pub(crate) const NOINDENT: &[&str] = &[
        "INTERSECT",
        "INTERSECT ALL",
        "MINUS",
        "UNION",
        "UNION ALL",
    ];
    pub(crate) static DIALECT: Dialect = Dialect {
        reserved_words: RESERVED,
        reserved_top_level: TOP,
        reserved_newline: NEWLINE,
        reserved_top_level_no_indent: NOINDENT,
        string_types: &[StringType::DoubleQuote, StringType::SingleQuote, StringType::Backtick, StringType::Brackets],
        open_parens: &["("],
        close_parens: &[")"],
        indexed_placeholders: &['?'],
        named_placeholders: &[':'],
        line_comments: &["--"],
        special_word_chars: &['#', '@'],
        extra_operators: &["**", "!=", "!>", "!>", "||"],
        override_kind: OverrideKind::None,
    };
}

pub(crate) static DB2: Dialect = db2::DIALECT;

